import "./globals.css";
import Link from "next/link";

/* Provides the layout for each page, including a navigation.
@param children Provides page to render inside the root layout.*/
export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </head>
      <body id="__next">
         {/* Navigation links to all relevant pages. */}
        <nav className="border-solid border-2">
          <div className="navbar bg-base-100 text-base-100">
            <div className="navbar-start">
              <Link href="/" className="btn btn-ghost normal-case text-xl bg-custom-first hover:bg-custom-second">
                StudentenKueche
              </Link>
            </div>
            <div className="navbar-center hidden lg:flex">
              <ul className="menu menu-horizontal p-0 bg-custom-first rounded-xl">
                <li className="">
                  <Link href="/recipes">Rezepte</Link>
                </li>
                <li>
                  <Link href="/favorites">Favoriten</Link>
                </li>
                <li>
                  <Link href="/my-recipes">Meine Rezepte</Link>
                </li>
                <li>
                  <Link href="/recipes/create-recipe">Neues Rezept</Link>
                </li>
              </ul>
            </div>
            <div className="navbar-end pr-2 ">
              <Link
                className="btn btn-ghost normal-case text-xl bg-custom-first hover:bg-custom-second"
                href="/profile"
              >
                Profil
              </Link>
              {/*               <Link href="/recipes/123">Rezept mit id 123</Link> */}
            </div>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
