name: Build and Test Spring Repository

on: push

jobs:
# Spring Boot Backend
  backend:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Actions
        uses: actions/checkout@v3
      - name: Moving directory
        run: mv -f recipe_backend/* .
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin
          cache: gradle
          
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
    
      - name: Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
          
      - name: Execute Gradle build
        run: ./gradlew build --scan
        

# Nextjs Frontend
#  frontend:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#      - run: mv -f recipe_frontend/* .
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 16
#      - run: npm build && npm test

